### PR TITLE
Develop week1 v.2

### PR DESCRIPTION
**Pull request by tonyChou-tech**
代恆，修正3個issue，請老師審查，謝謝
http://35.78.19.239:3000/api/attractions?page=1
http://35.78.19.239:3000/api/attractions?page=0&keyword=藝術
http://35.78.19.239:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Better. But response format of http://35.78.19.239:3000/api/attraction/10 is still incorrect.

You don't need to close pull request. Just push new commits to `develop` branch and ask me to review again here.

**Comment by tonyChou-tech** [comment]
代恆
更新attractionId API 的response格式

**Comment by cwpeng** [comment]
Try to ask me to review again from right side of this page.

**Review by cwpeng — APPROVED** [review]
OK. Good Job.

**Pull request merged**
